name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Building kernel
      run: |
        cd ${GITHUB_WORKSPACE}
        chmod +x build
        ./build
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        
    - name: Add and Commit
      run: |
        git add -A
        git commit -m "initial commit"
        git push
        
