name: Tes doang

on:
  workflow_dispatch:

jobs:
  making-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Nyoba
      run: |
        cd ${GITHUB_WORKSPACE}
        mkdir ndok
        mv * ndok
        wget https://github.com/Galaxy-A02-dev/android_kernel_samsung_a02/archive/refs/heads/Android-Q.zip
        ls
        echo ------------lagi--------------
        echo ------------download----------
        echo ------------bentar------------
        echo ------------bentar------------
        echo ------------bentar------------
        unzip Android-Q.zip
        ls
        echo ------------cek---------------
        echo ------------direktori---------
        echo ------------bentar------------
        echo ------------bentar------------
        echo ------------bentar------------
        cd android_kernel_samsung_a02-Android-Q
        ls
        echo ------------cek---------------
        echo ------------direktori---------
        echo ------------bentar------------
        echo ------------bentar------------
        echo ------------bentar------------
        cd ${GITHUB_WORKSPACE}
        mv android_kernel_samsung_a02-Android-Q/* .
        rm -rf android_kernel_samsung_a02
        rm -rf ndok
        rm Android-Q.zip
        ls
        echo ------------bentar------------
        echo ------------bentar------------
        echo ------------bentar------------
        echo ------------bentar------------
        echo ------------bentar------------
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        
    - name: Add and Commit file
      run: |
        git add -A
        git commit -m "initial commit"
        git push
        
