name: Tes doang

on:
  workflow_dispatch:

jobs:
  making-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Nyoba
      run: |
        cd ${GITHUB_WORKSPACE}
        mkdir -p tempe
        cd tempe
        git clone https://github.com/Galaxy-A02-dev/android_kernel_samsung_a02 -b Android-Q
        rm Android-Q.zip
        echo ------------bentar------------       
        ls
        echo ------------ok dah------------
        
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        
    - name: Add and Commit file
      run: |
        git add -A
        git commit -m "Ready to download"
        git push
        
